### ISSUE TITLE
Contact request with admiral team

### ISSUE THREAD

**Issue by rossfarrugia** [CDC-DNPAO/WHOanthro#1]
Hi developers,

I'm interested to connect around your work on this R package. I sponsor a family of R packages called admiral used for creating ADaM for clinical trials ([link](https://pharmaverse.github.io/admiral/index.html)). This is a collaboration from currently 7 pharma companies helping to ensure a harmonized and simpler way for all of our industry to report clinical trials, and we make all the code freely available with a permissive open source license.

We're interested in looking into making a package extension to help with pediatric studies and we saw child growth/development charts as a suitable place to start. I wanted to ask if anyone from your team would be willing to take a short call to discuss your work in this space. 

Thanks,
Ross

**Comment by CDC-DNPAO** [comment]
Ross, I'm David Freedman, and I wrote the code for cdcanthro and
whoanthro.  I'm retired now, but I'd be happy to talk with you.  I'm going
out of town, but will be back on Wed.

I'm sure if you suggest 2 times later in the week, one will work for me.
Wed after 2 pm, Thurs morning, and any time on Friday look good for me.

take care, David Freedman

**Comment by rossfarrugia** [comment]
Thank you David!

I'm based in UK, so sending some timeslots in GMT afternoon time - assuming you're based somewhere in US one of these will hopefully work for you. I'm free anytime Thurs 2-4PM or Friday 4-5PM. I'd really appreciate 30 minutes of your time at whichever slot works best and send me a contact email and I can get a meeting arranged.

**Comment by CDC-DNPAO** [comment]
Ross - the Friday time would be fine - I'm on the E Coast (11 am, my
time).  My email is in the cc and my phone is 1 678 671 1881

David

**Comment by rossfarrugia** [comment]
Thanks David! 

Sounds good to me. I don't see the email cc here in GitHub. My email is ross.farrugia@roche.com - if you drop me an email so I have your email address then I can set us up a Google hangout to use for the call.
